---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: qlik/gradle
    tag: latest

inputs:
- name: easy-eureka

outputs:
- name: builds

run:
  path: easy-eureka/ci/build.sh